apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-resource-operator
spec:
  template:
    spec:
      containers:
        - name: resource-operator
          args:
            - --logging-level=debug
            - --logging-format=logfmt
