resources:
- deployment.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: temporalio/resource-operator
  newName: temporalio/resource-operator
  newTag: latest
