apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: temporal-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: temporal-resource-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: temporal-resource-operator
subjects:
- kind: ServiceAccount
  name: temporal-resource-operator
  namespace: temporal-resource-operator
