apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: temporal-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: temporal-resource-operator
  namespace: temporal-resource-operator
